### ISSUE TITLE
exported OBJ render is wrong

### ISSUE THREAD

**Issue by bizkitj** [wblut/HE_Mesh#60]
Hello, while I am rendering  the exported obj in 3dsmax, the rendering is wrong. 
```
import peasy.*;
import wblut.nurbs.*;
import wblut.hemesh.*;
import wblut.core.*;
import wblut.geom.*;
import wblut.processing.*;
import wblut.math.*;

HE_Mesh mesh;
WB_Render render;
PeasyCam cam;
void setup (){
 size(600,600,P3D);
 cam = new PeasyCam(this,200);
 HEC_Cube cube = new HEC_Cube(50,1,1,1);
 mesh = new HE_Mesh(cube);
 render = new WB_Render(this);
}

void draw(){
background(90);
noStroke();
render.drawFaces(mesh);
stroke(0);
render.drawEdges(mesh);

}

void keyPressed() {
  if (key =='s') {
    HET_Export.saveToOBJ(mesh, sketchPath("meshes6"), "test");
    println("saved");
  }
}
```

Attaches is the rendering.
![test_render](https://cloud.githubusercontent.com/assets/25093538/24543308/bb05e808-1631-11e7-93e3-fb4c69edc3d5.jpg)

**Comment by bizkitj** [comment]
update:
exported as stl, rendering is right. 
On the attached img, left one is the imported obj, right one is the imported stl. But, need the colored obj to be rendered correctly.
![test_render](https://cloud.githubusercontent.com/assets/25093538/24547581/290cc7b6-1643-11e7-8278-8e6db20e3167.jpg)

**Comment by wblut** [comment]
This is most probably not an issue with HE_Mesh. Have you tried switching auto smooth off in 3dsmax? Exported obj files contain vertex normals which probably lead to this kind of rendering. Stl files do not contain vertex normals.
There is no way for me to check this as I have no access to expensive software like 3DSMax, one of the reasons I work in Processing rather than using MaxScript for something like this.
